// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LogConsumer.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CLIPPY.Log {

  /// <summary>Holder for reflection information generated from LogConsumer.proto</summary>
  public static partial class LogConsumerReflection {

    #region Descriptor
    /// <summary>File descriptor for LogConsumer.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LogConsumerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFMb2dDb25zdW1lci5wcm90bxIKQ0xJUFBZLmxvZxoPTG9nUmVjb3JkLnBy",
            "b3RvGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8yUQoLTG9nQ29uc3Vt",
            "ZXISQgoPU3VibWl0TG9nUmVjb3JkEhUuQ0xJUFBZLmxvZy5Mb2dSZWNvcmQa",
            "Fi5nb29nbGUucHJvdG9idWYuRW1wdHkiAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CLIPPY.Log.LogRecordReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
