// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Logger.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CLIPPY.Log {

  /// <summary>Holder for reflection information generated from Logger.proto</summary>
  public static partial class LoggerReflection {

    #region Descriptor
    /// <summary>File descriptor for Logger.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LoggerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxMb2dnZXIucHJvdG8SCkNMSVBQWS5sb2caD0xvZ1JlY29yZC5wcm90bxob",
            "Z29vZ2xlL3Byb3RvYnVmL2VtcHR5LnByb3RvMkwKBkxvZ2dlchJCCg9TdWJt",
            "aXRMb2dSZWNvcmQSFS5DTElQUFkubG9nLkxvZ1JlY29yZBoWLmdvb2dsZS5w",
            "cm90b2J1Zi5FbXB0eSIAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CLIPPY.Log.LogRecordReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
