// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MotionPlannerServer.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CLIPPY.Control {

  /// <summary>Holder for reflection information generated from MotionPlannerServer.proto</summary>
  public static partial class MotionPlannerServerReflection {

    #region Descriptor
    /// <summary>File descriptor for MotionPlannerServer.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MotionPlannerServerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlNb3Rpb25QbGFubmVyU2VydmVyLnByb3RvEg5DTElQUFkuY29udHJvbBoO",
            "V2F5cG9pbnQucHJvdG8aE0NvbnRyb2xUYXJnZXQucHJvdG8aG2dvb2dsZS9w",
            "cm90b2J1Zi9lbXB0eS5wcm90bzKrAQoTTW90aW9uUGxhbm5lclNlcnZlchJE",
            "Cg5TdWJtaXRXYXlwb2ludBIYLkNMSVBQWS5jb250cm9sLldheXBvaW50GhYu",
            "Z29vZ2xlLnByb3RvYnVmLkVtcHR5IgASTgoTU3VibWl0Q29udHJvbFRhcmdl",
            "dBIdLkNMSVBQWS5jb250cm9sLkNvbnRyb2xUYXJnZXQaFi5nb29nbGUucHJv",
            "dG9idWYuRW1wdHkiAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CLIPPY.Control.WaypointReflection.Descriptor, global::CLIPPY.Control.ControlTargetReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
