// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SystemTuner.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CLIPPY.Control {

  /// <summary>Holder for reflection information generated from SystemTuner.proto</summary>
  public static partial class SystemTunerReflection {

    #region Descriptor
    /// <summary>File descriptor for SystemTuner.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SystemTunerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFTeXN0ZW1UdW5lci5wcm90bxIOQ0xJUFBZLmNvbnRyb2waE0NvbnRyb2xU",
            "YXJnZXQucHJvdG8aEkNvbnRyb2xHYWlucy5wcm90bxoSQ29udHJvbFN0eWxl",
            "LnByb3RvGhFTeXN0ZW1TdGF0ZS5wcm90bxobZ29vZ2xlL3Byb3RvYnVmL2Vt",
            "cHR5LnByb3RvMloKC1N5c3RlbVR1bmVyEksKD1NldENvbnRyb2xHYWlucxIc",
            "LkNMSVBQWS5jb250cm9sLkNvbnRyb2xHYWlucxoWLmdvb2dsZS5wcm90b2J1",
            "Zi5FbXB0eSIAKAEy7wEKEFN5c3RlbURhdGFTZXJ2ZXISRwoMR2V0U3lzdGVt",
            "SURzEhouQ0xJUFBZLmNvbnRyb2wuU3lzdGVtVGFncxoZLkNMSVBQWS5jb250",
            "cm9sLlN5c3RlbUlEcyIAEkUKDUdldFN5c3RlbVRhZ3MSFi5nb29nbGUucHJv",
            "dG9idWYuRW1wdHkaGi5DTElQUFkuY29udHJvbC5TeXN0ZW1UYWdzIgASSwoN",
            "R2V0U3lzdGVtRGF0YRIZLkNMSVBQWS5jb250cm9sLlN5c3RlbUlEcxobLkNM",
            "SVBQWS5jb250cm9sLlN5c3RlbVN0YXRlIgAwAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CLIPPY.Control.ControlTargetReflection.Descriptor, global::CLIPPY.Control.ControlGainsReflection.Descriptor, global::CLIPPY.Control.ControlStyleReflection.Descriptor, global::CLIPPY.Control.SystemStateReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
