// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Urgency.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CLIPPY.Control {

  /// <summary>Holder for reflection information generated from Urgency.proto</summary>
  public static partial class UrgencyReflection {

    #region Descriptor
    /// <summary>File descriptor for Urgency.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UrgencyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1VcmdlbmN5LnByb3RvEg5DTElQUFkuY29udHJvbCpUCgdVcmdlbmN5Eg4K",
            "ClVOQVNTSUdORUQQABIQCgxIWVBPVEhFVElDQUwQARIOCgpTVUdHRVNUSU9O",
            "EAISCwoHUkVRVUVTVBADEgoKBkRFTUFORBAEYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CLIPPY.Control.Urgency), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Urgency {
    /// <summary>
    /// There is no urgency associated with this waypoint
    /// </summary>
    [pbr::OriginalName("UNASSIGNED")] Unassigned = 0,
    /// <summary>
    /// It's just an idea (candidate for a selection process)
    /// </summary>
    [pbr::OriginalName("HYPOTHETICAL")] Hypothetical = 1,
    /// <summary>
    /// You might want to look at this (normal priority for sensor-driven models)
    /// </summary>
    [pbr::OriginalName("SUGGESTION")] Suggestion = 2,
    /// <summary>
    /// Yes please (normal priority for user guidance)
    /// </summary>
    [pbr::OriginalName("REQUEST")] Request = 3,
    /// <summary>
    /// There is no highway option (reserved for safety?)
    /// </summary>
    [pbr::OriginalName("DEMAND")] Demand = 4,
  }

  #endregion

}

#endregion Designer generated code
