// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WaypointShufflers.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CLIPPY.Control {

  /// <summary>Holder for reflection information generated from WaypointShufflers.proto</summary>
  public static partial class WaypointShufflersReflection {

    #region Descriptor
    /// <summary>File descriptor for WaypointShufflers.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WaypointShufflersReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdXYXlwb2ludFNodWZmbGVycy5wcm90bxIOQ0xJUFBZLmNvbnRyb2waDldh",
            "eXBvaW50LnByb3RvGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8yVgoO",
            "V2F5cG9pbnRTZXJ2ZXISRAoMR2V0V2F5cG9pbnRzEhYuZ29vZ2xlLnByb3Rv",
            "YnVmLkVtcHR5GhguQ0xJUFBZLmNvbnRyb2wuV2F5cG9pbnQiADABMlUKDVdh",
            "eXBvaW50RWF0ZXISRAoOSW5nZXN0V2F5cG9pbnQSGC5DTElQUFkuY29udHJv",
            "bC5XYXlwb2ludBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CLIPPY.Control.WaypointReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
