services:
  protos:
    build: ./protos
  mq:
    build: ./mq
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
  log:
    build:
      context: .
      dockerfile: ./log/Dockerfile
    volumes:
      - ./d/log:/d
    depends_on:
      mq:
        condition: service_healthy
