// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotController.proto

package CLIPPY.control;

public final class RobotControllerOuterClass {
  private RobotControllerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025RobotController.proto\022\016CLIPPY.control\032" +
      "\023ControlTarget.proto\032\022ControlGains.proto" +
      "\032\022ControlStyle.proto\032\033google/protobuf/em" +
      "pty.proto2\372\001\n\017RobotController\022N\n\023SubmitC" +
      "ontrolTarget\022\035.CLIPPY.control.ControlTar" +
      "get\032\026.google.protobuf.Empty\"\000\022L\n\022SubmitC" +
      "ontrolGains\022\034.CLIPPY.control.ControlGain" +
      "s\032\026.google.protobuf.Empty\"\000\022I\n\017SetContro" +
      "lStyle\022\034.CLIPPY.control.ControlStyle\032\026.g" +
      "oogle.protobuf.Empty\"\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          CLIPPY.control.ControlTargetOuterClass.getDescriptor(),
          CLIPPY.control.ControlGainsOuterClass.getDescriptor(),
          CLIPPY.control.ControlStyleOuterClass.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    CLIPPY.control.ControlTargetOuterClass.getDescriptor();
    CLIPPY.control.ControlGainsOuterClass.getDescriptor();
    CLIPPY.control.ControlStyleOuterClass.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
