// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Waypoint.proto

package CLIPPY.control;

public final class WaypointOuterClass {
  private WaypointOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code CLIPPY.control.WaypointType}
   */
  public enum WaypointType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * We don't know anything about this waypoint's moral value.
     * </pre>
     *
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <pre>
     * We could not care less what's here.
     * </pre>
     *
     * <code>NEUTRAL = 1;</code>
     */
    NEUTRAL(1),
    /**
     * <pre>
     * The way is shut.
     * </pre>
     *
     * <code>OBSTACLE = 2;</code>
     */
    OBSTACLE(2),
    /**
     * <pre>
     * This place has been emptied of whatever was there.
     * </pre>
     *
     * <code>FREE = 3;</code>
     */
    FREE(3),
    /**
     * <pre>
     * LEROOOOOOY JENKIIIIIIIINS
     * </pre>
     *
     * <code>TARGET = 4;</code>
     */
    TARGET(4),
    /**
     * <pre>
     * You are here.
     * </pre>
     *
     * <code>SELF = 5;</code>
     */
    SELF(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * We don't know anything about this waypoint's moral value.
     * </pre>
     *
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * We could not care less what's here.
     * </pre>
     *
     * <code>NEUTRAL = 1;</code>
     */
    public static final int NEUTRAL_VALUE = 1;
    /**
     * <pre>
     * The way is shut.
     * </pre>
     *
     * <code>OBSTACLE = 2;</code>
     */
    public static final int OBSTACLE_VALUE = 2;
    /**
     * <pre>
     * This place has been emptied of whatever was there.
     * </pre>
     *
     * <code>FREE = 3;</code>
     */
    public static final int FREE_VALUE = 3;
    /**
     * <pre>
     * LEROOOOOOY JENKIIIIIIIINS
     * </pre>
     *
     * <code>TARGET = 4;</code>
     */
    public static final int TARGET_VALUE = 4;
    /**
     * <pre>
     * You are here.
     * </pre>
     *
     * <code>SELF = 5;</code>
     */
    public static final int SELF_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static WaypointType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static WaypointType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return NEUTRAL;
        case 2: return OBSTACLE;
        case 3: return FREE;
        case 4: return TARGET;
        case 5: return SELF;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<WaypointType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        WaypointType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<WaypointType>() {
            public WaypointType findValueByNumber(int number) {
              return WaypointType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CLIPPY.control.WaypointOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final WaypointType[] VALUES = values();

    public static WaypointType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private WaypointType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CLIPPY.control.WaypointType)
  }

  public interface WaypointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CLIPPY.control.Waypoint)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     * @return The timestamp.
     */
    com.google.protobuf.Timestamp getTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

    /**
     * <code>.CLIPPY.control.WaypointType waypoint_type = 2;</code>
     * @return The enum numeric value on the wire for waypointType.
     */
    int getWaypointTypeValue();
    /**
     * <code>.CLIPPY.control.WaypointType waypoint_type = 2;</code>
     * @return The waypointType.
     */
    CLIPPY.control.WaypointOuterClass.WaypointType getWaypointType();

    /**
     * <code>.CLIPPY.control.Urgency urgency = 3;</code>
     * @return The enum numeric value on the wire for urgency.
     */
    int getUrgencyValue();
    /**
     * <code>.CLIPPY.control.Urgency urgency = 3;</code>
     * @return The urgency.
     */
    CLIPPY.control.UrgencyOuterClass.Urgency getUrgency();

    /**
     * <pre>
     * XYZ coordinates of the waypoint
     * </pre>
     *
     * <code>double x = 7;</code>
     * @return The x.
     */
    double getX();

    /**
     * <code>double y = 8;</code>
     * @return The y.
     */
    double getY();

    /**
     * <code>double z = 9;</code>
     * @return The z.
     */
    double getZ();

    /**
     * <pre>
     * Rotation angles of the waypoint, in radians
     * Consider a quaternion?
     * </pre>
     *
     * <code>double t_xy = 10;</code>
     * @return The tXy.
     */
    double getTXy();

    /**
     * <pre>
     * Width of margin of error on each axis
     * </pre>
     *
     * <code>double dx = 13;</code>
     * @return The dx.
     */
    double getDx();

    /**
     * <code>double dy = 14;</code>
     * @return The dy.
     */
    double getDy();

    /**
     * <code>double dz = 15;</code>
     * @return The dz.
     */
    double getDz();

    /**
     * <code>double dt_xy = 16;</code>
     * @return The dtXy.
     */
    double getDtXy();
  }
  /**
   * Protobuf type {@code CLIPPY.control.Waypoint}
   */
  public static final class Waypoint extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CLIPPY.control.Waypoint)
      WaypointOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Waypoint.newBuilder() to construct.
    private Waypoint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Waypoint() {
      waypointType_ = 0;
      urgency_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Waypoint();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CLIPPY.control.WaypointOuterClass.internal_static_CLIPPY_control_Waypoint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CLIPPY.control.WaypointOuterClass.internal_static_CLIPPY_control_Waypoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CLIPPY.control.WaypointOuterClass.Waypoint.class, CLIPPY.control.WaypointOuterClass.Waypoint.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp timestamp_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }

    public static final int WAYPOINT_TYPE_FIELD_NUMBER = 2;
    private int waypointType_ = 0;
    /**
     * <code>.CLIPPY.control.WaypointType waypoint_type = 2;</code>
     * @return The enum numeric value on the wire for waypointType.
     */
    @java.lang.Override public int getWaypointTypeValue() {
      return waypointType_;
    }
    /**
     * <code>.CLIPPY.control.WaypointType waypoint_type = 2;</code>
     * @return The waypointType.
     */
    @java.lang.Override public CLIPPY.control.WaypointOuterClass.WaypointType getWaypointType() {
      CLIPPY.control.WaypointOuterClass.WaypointType result = CLIPPY.control.WaypointOuterClass.WaypointType.forNumber(waypointType_);
      return result == null ? CLIPPY.control.WaypointOuterClass.WaypointType.UNRECOGNIZED : result;
    }

    public static final int URGENCY_FIELD_NUMBER = 3;
    private int urgency_ = 0;
    /**
     * <code>.CLIPPY.control.Urgency urgency = 3;</code>
     * @return The enum numeric value on the wire for urgency.
     */
    @java.lang.Override public int getUrgencyValue() {
      return urgency_;
    }
    /**
     * <code>.CLIPPY.control.Urgency urgency = 3;</code>
     * @return The urgency.
     */
    @java.lang.Override public CLIPPY.control.UrgencyOuterClass.Urgency getUrgency() {
      CLIPPY.control.UrgencyOuterClass.Urgency result = CLIPPY.control.UrgencyOuterClass.Urgency.forNumber(urgency_);
      return result == null ? CLIPPY.control.UrgencyOuterClass.Urgency.UNRECOGNIZED : result;
    }

    public static final int X_FIELD_NUMBER = 7;
    private double x_ = 0D;
    /**
     * <pre>
     * XYZ coordinates of the waypoint
     * </pre>
     *
     * <code>double x = 7;</code>
     * @return The x.
     */
    @java.lang.Override
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 8;
    private double y_ = 0D;
    /**
     * <code>double y = 8;</code>
     * @return The y.
     */
    @java.lang.Override
    public double getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 9;
    private double z_ = 0D;
    /**
     * <code>double z = 9;</code>
     * @return The z.
     */
    @java.lang.Override
    public double getZ() {
      return z_;
    }

    public static final int T_XY_FIELD_NUMBER = 10;
    private double tXy_ = 0D;
    /**
     * <pre>
     * Rotation angles of the waypoint, in radians
     * Consider a quaternion?
     * </pre>
     *
     * <code>double t_xy = 10;</code>
     * @return The tXy.
     */
    @java.lang.Override
    public double getTXy() {
      return tXy_;
    }

    public static final int DX_FIELD_NUMBER = 13;
    private double dx_ = 0D;
    /**
     * <pre>
     * Width of margin of error on each axis
     * </pre>
     *
     * <code>double dx = 13;</code>
     * @return The dx.
     */
    @java.lang.Override
    public double getDx() {
      return dx_;
    }

    public static final int DY_FIELD_NUMBER = 14;
    private double dy_ = 0D;
    /**
     * <code>double dy = 14;</code>
     * @return The dy.
     */
    @java.lang.Override
    public double getDy() {
      return dy_;
    }

    public static final int DZ_FIELD_NUMBER = 15;
    private double dz_ = 0D;
    /**
     * <code>double dz = 15;</code>
     * @return The dz.
     */
    @java.lang.Override
    public double getDz() {
      return dz_;
    }

    public static final int DT_XY_FIELD_NUMBER = 16;
    private double dtXy_ = 0D;
    /**
     * <code>double dt_xy = 16;</code>
     * @return The dtXy.
     */
    @java.lang.Override
    public double getDtXy() {
      return dtXy_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getTimestamp());
      }
      if (waypointType_ != CLIPPY.control.WaypointOuterClass.WaypointType.UNKNOWN.getNumber()) {
        output.writeEnum(2, waypointType_);
      }
      if (urgency_ != CLIPPY.control.UrgencyOuterClass.Urgency.UNASSIGNED.getNumber()) {
        output.writeEnum(3, urgency_);
      }
      if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
        output.writeDouble(7, x_);
      }
      if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
        output.writeDouble(8, y_);
      }
      if (java.lang.Double.doubleToRawLongBits(z_) != 0) {
        output.writeDouble(9, z_);
      }
      if (java.lang.Double.doubleToRawLongBits(tXy_) != 0) {
        output.writeDouble(10, tXy_);
      }
      if (java.lang.Double.doubleToRawLongBits(dx_) != 0) {
        output.writeDouble(13, dx_);
      }
      if (java.lang.Double.doubleToRawLongBits(dy_) != 0) {
        output.writeDouble(14, dy_);
      }
      if (java.lang.Double.doubleToRawLongBits(dz_) != 0) {
        output.writeDouble(15, dz_);
      }
      if (java.lang.Double.doubleToRawLongBits(dtXy_) != 0) {
        output.writeDouble(16, dtXy_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTimestamp());
      }
      if (waypointType_ != CLIPPY.control.WaypointOuterClass.WaypointType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, waypointType_);
      }
      if (urgency_ != CLIPPY.control.UrgencyOuterClass.Urgency.UNASSIGNED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, urgency_);
      }
      if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, x_);
      }
      if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, y_);
      }
      if (java.lang.Double.doubleToRawLongBits(z_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, z_);
      }
      if (java.lang.Double.doubleToRawLongBits(tXy_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, tXy_);
      }
      if (java.lang.Double.doubleToRawLongBits(dx_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(13, dx_);
      }
      if (java.lang.Double.doubleToRawLongBits(dy_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(14, dy_);
      }
      if (java.lang.Double.doubleToRawLongBits(dz_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(15, dz_);
      }
      if (java.lang.Double.doubleToRawLongBits(dtXy_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(16, dtXy_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CLIPPY.control.WaypointOuterClass.Waypoint)) {
        return super.equals(obj);
      }
      CLIPPY.control.WaypointOuterClass.Waypoint other = (CLIPPY.control.WaypointOuterClass.Waypoint) obj;

      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
      }
      if (waypointType_ != other.waypointType_) return false;
      if (urgency_ != other.urgency_) return false;
      if (java.lang.Double.doubleToLongBits(getX())
          != java.lang.Double.doubleToLongBits(
              other.getX())) return false;
      if (java.lang.Double.doubleToLongBits(getY())
          != java.lang.Double.doubleToLongBits(
              other.getY())) return false;
      if (java.lang.Double.doubleToLongBits(getZ())
          != java.lang.Double.doubleToLongBits(
              other.getZ())) return false;
      if (java.lang.Double.doubleToLongBits(getTXy())
          != java.lang.Double.doubleToLongBits(
              other.getTXy())) return false;
      if (java.lang.Double.doubleToLongBits(getDx())
          != java.lang.Double.doubleToLongBits(
              other.getDx())) return false;
      if (java.lang.Double.doubleToLongBits(getDy())
          != java.lang.Double.doubleToLongBits(
              other.getDy())) return false;
      if (java.lang.Double.doubleToLongBits(getDz())
          != java.lang.Double.doubleToLongBits(
              other.getDz())) return false;
      if (java.lang.Double.doubleToLongBits(getDtXy())
          != java.lang.Double.doubleToLongBits(
              other.getDtXy())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      hash = (37 * hash) + WAYPOINT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + waypointType_;
      hash = (37 * hash) + URGENCY_FIELD_NUMBER;
      hash = (53 * hash) + urgency_;
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getX()));
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getY()));
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getZ()));
      hash = (37 * hash) + T_XY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTXy()));
      hash = (37 * hash) + DX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDx()));
      hash = (37 * hash) + DY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDy()));
      hash = (37 * hash) + DZ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDz()));
      hash = (37 * hash) + DT_XY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDtXy()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CLIPPY.control.WaypointOuterClass.Waypoint parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CLIPPY.control.WaypointOuterClass.Waypoint parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CLIPPY.control.WaypointOuterClass.Waypoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CLIPPY.control.WaypointOuterClass.Waypoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CLIPPY.control.WaypointOuterClass.Waypoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CLIPPY.control.WaypointOuterClass.Waypoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CLIPPY.control.WaypointOuterClass.Waypoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CLIPPY.control.WaypointOuterClass.Waypoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static CLIPPY.control.WaypointOuterClass.Waypoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static CLIPPY.control.WaypointOuterClass.Waypoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CLIPPY.control.WaypointOuterClass.Waypoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CLIPPY.control.WaypointOuterClass.Waypoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CLIPPY.control.WaypointOuterClass.Waypoint prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CLIPPY.control.Waypoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CLIPPY.control.Waypoint)
        CLIPPY.control.WaypointOuterClass.WaypointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CLIPPY.control.WaypointOuterClass.internal_static_CLIPPY_control_Waypoint_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CLIPPY.control.WaypointOuterClass.internal_static_CLIPPY_control_Waypoint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CLIPPY.control.WaypointOuterClass.Waypoint.class, CLIPPY.control.WaypointOuterClass.Waypoint.Builder.class);
      }

      // Construct using CLIPPY.control.WaypointOuterClass.Waypoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTimestampFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestamp_ = null;
        if (timestampBuilder_ != null) {
          timestampBuilder_.dispose();
          timestampBuilder_ = null;
        }
        waypointType_ = 0;
        urgency_ = 0;
        x_ = 0D;
        y_ = 0D;
        z_ = 0D;
        tXy_ = 0D;
        dx_ = 0D;
        dy_ = 0D;
        dz_ = 0D;
        dtXy_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CLIPPY.control.WaypointOuterClass.internal_static_CLIPPY_control_Waypoint_descriptor;
      }

      @java.lang.Override
      public CLIPPY.control.WaypointOuterClass.Waypoint getDefaultInstanceForType() {
        return CLIPPY.control.WaypointOuterClass.Waypoint.getDefaultInstance();
      }

      @java.lang.Override
      public CLIPPY.control.WaypointOuterClass.Waypoint build() {
        CLIPPY.control.WaypointOuterClass.Waypoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CLIPPY.control.WaypointOuterClass.Waypoint buildPartial() {
        CLIPPY.control.WaypointOuterClass.Waypoint result = new CLIPPY.control.WaypointOuterClass.Waypoint(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(CLIPPY.control.WaypointOuterClass.Waypoint result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestamp_ = timestampBuilder_ == null
              ? timestamp_
              : timestampBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.waypointType_ = waypointType_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.urgency_ = urgency_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.x_ = x_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.y_ = y_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.z_ = z_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.tXy_ = tXy_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.dx_ = dx_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.dy_ = dy_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.dz_ = dz_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.dtXy_ = dtXy_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CLIPPY.control.WaypointOuterClass.Waypoint) {
          return mergeFrom((CLIPPY.control.WaypointOuterClass.Waypoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CLIPPY.control.WaypointOuterClass.Waypoint other) {
        if (other == CLIPPY.control.WaypointOuterClass.Waypoint.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        if (other.waypointType_ != 0) {
          setWaypointTypeValue(other.getWaypointTypeValue());
        }
        if (other.urgency_ != 0) {
          setUrgencyValue(other.getUrgencyValue());
        }
        if (other.getX() != 0D) {
          setX(other.getX());
        }
        if (other.getY() != 0D) {
          setY(other.getY());
        }
        if (other.getZ() != 0D) {
          setZ(other.getZ());
        }
        if (other.getTXy() != 0D) {
          setTXy(other.getTXy());
        }
        if (other.getDx() != 0D) {
          setDx(other.getDx());
        }
        if (other.getDy() != 0D) {
          setDy(other.getDy());
        }
        if (other.getDz() != 0D) {
          setDz(other.getDz());
        }
        if (other.getDtXy() != 0D) {
          setDtXy(other.getDtXy());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getTimestampFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                waypointType_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                urgency_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 57: {
                x_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 57
              case 65: {
                y_ = input.readDouble();
                bitField0_ |= 0x00000010;
                break;
              } // case 65
              case 73: {
                z_ = input.readDouble();
                bitField0_ |= 0x00000020;
                break;
              } // case 73
              case 81: {
                tXy_ = input.readDouble();
                bitField0_ |= 0x00000040;
                break;
              } // case 81
              case 105: {
                dx_ = input.readDouble();
                bitField0_ |= 0x00000080;
                break;
              } // case 105
              case 113: {
                dy_ = input.readDouble();
                bitField0_ |= 0x00000100;
                break;
              } // case 113
              case 121: {
                dz_ = input.readDouble();
                bitField0_ |= 0x00000200;
                break;
              } // case 121
              case 129: {
                dtXy_ = input.readDouble();
                bitField0_ |= 0x00000400;
                break;
              } // case 129
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Timestamp timestamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       * @return Whether the timestamp field is set.
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       * @return The timestamp.
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
        } else {
          timestampBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public Builder setTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            timestamp_ != null &&
            timestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getTimestampBuilder().mergeFrom(value);
          } else {
            timestamp_ = value;
          }
        } else {
          timestampBuilder_.mergeFrom(value);
        }
        if (timestamp_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = null;
        if (timestampBuilder_ != null) {
          timestampBuilder_.dispose();
          timestampBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }

      private int waypointType_ = 0;
      /**
       * <code>.CLIPPY.control.WaypointType waypoint_type = 2;</code>
       * @return The enum numeric value on the wire for waypointType.
       */
      @java.lang.Override public int getWaypointTypeValue() {
        return waypointType_;
      }
      /**
       * <code>.CLIPPY.control.WaypointType waypoint_type = 2;</code>
       * @param value The enum numeric value on the wire for waypointType to set.
       * @return This builder for chaining.
       */
      public Builder setWaypointTypeValue(int value) {
        waypointType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.CLIPPY.control.WaypointType waypoint_type = 2;</code>
       * @return The waypointType.
       */
      @java.lang.Override
      public CLIPPY.control.WaypointOuterClass.WaypointType getWaypointType() {
        CLIPPY.control.WaypointOuterClass.WaypointType result = CLIPPY.control.WaypointOuterClass.WaypointType.forNumber(waypointType_);
        return result == null ? CLIPPY.control.WaypointOuterClass.WaypointType.UNRECOGNIZED : result;
      }
      /**
       * <code>.CLIPPY.control.WaypointType waypoint_type = 2;</code>
       * @param value The waypointType to set.
       * @return This builder for chaining.
       */
      public Builder setWaypointType(CLIPPY.control.WaypointOuterClass.WaypointType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        waypointType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.CLIPPY.control.WaypointType waypoint_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearWaypointType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        waypointType_ = 0;
        onChanged();
        return this;
      }

      private int urgency_ = 0;
      /**
       * <code>.CLIPPY.control.Urgency urgency = 3;</code>
       * @return The enum numeric value on the wire for urgency.
       */
      @java.lang.Override public int getUrgencyValue() {
        return urgency_;
      }
      /**
       * <code>.CLIPPY.control.Urgency urgency = 3;</code>
       * @param value The enum numeric value on the wire for urgency to set.
       * @return This builder for chaining.
       */
      public Builder setUrgencyValue(int value) {
        urgency_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.CLIPPY.control.Urgency urgency = 3;</code>
       * @return The urgency.
       */
      @java.lang.Override
      public CLIPPY.control.UrgencyOuterClass.Urgency getUrgency() {
        CLIPPY.control.UrgencyOuterClass.Urgency result = CLIPPY.control.UrgencyOuterClass.Urgency.forNumber(urgency_);
        return result == null ? CLIPPY.control.UrgencyOuterClass.Urgency.UNRECOGNIZED : result;
      }
      /**
       * <code>.CLIPPY.control.Urgency urgency = 3;</code>
       * @param value The urgency to set.
       * @return This builder for chaining.
       */
      public Builder setUrgency(CLIPPY.control.UrgencyOuterClass.Urgency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        urgency_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.CLIPPY.control.Urgency urgency = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrgency() {
        bitField0_ = (bitField0_ & ~0x00000004);
        urgency_ = 0;
        onChanged();
        return this;
      }

      private double x_ ;
      /**
       * <pre>
       * XYZ coordinates of the waypoint
       * </pre>
       *
       * <code>double x = 7;</code>
       * @return The x.
       */
      @java.lang.Override
      public double getX() {
        return x_;
      }
      /**
       * <pre>
       * XYZ coordinates of the waypoint
       * </pre>
       *
       * <code>double x = 7;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(double value) {

        x_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * XYZ coordinates of the waypoint
       * </pre>
       *
       * <code>double x = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000008);
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>double y = 8;</code>
       * @return The y.
       */
      @java.lang.Override
      public double getY() {
        return y_;
      }
      /**
       * <code>double y = 8;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(double value) {

        y_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>double y = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000010);
        y_ = 0D;
        onChanged();
        return this;
      }

      private double z_ ;
      /**
       * <code>double z = 9;</code>
       * @return The z.
       */
      @java.lang.Override
      public double getZ() {
        return z_;
      }
      /**
       * <code>double z = 9;</code>
       * @param value The z to set.
       * @return This builder for chaining.
       */
      public Builder setZ(double value) {

        z_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>double z = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000020);
        z_ = 0D;
        onChanged();
        return this;
      }

      private double tXy_ ;
      /**
       * <pre>
       * Rotation angles of the waypoint, in radians
       * Consider a quaternion?
       * </pre>
       *
       * <code>double t_xy = 10;</code>
       * @return The tXy.
       */
      @java.lang.Override
      public double getTXy() {
        return tXy_;
      }
      /**
       * <pre>
       * Rotation angles of the waypoint, in radians
       * Consider a quaternion?
       * </pre>
       *
       * <code>double t_xy = 10;</code>
       * @param value The tXy to set.
       * @return This builder for chaining.
       */
      public Builder setTXy(double value) {

        tXy_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Rotation angles of the waypoint, in radians
       * Consider a quaternion?
       * </pre>
       *
       * <code>double t_xy = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearTXy() {
        bitField0_ = (bitField0_ & ~0x00000040);
        tXy_ = 0D;
        onChanged();
        return this;
      }

      private double dx_ ;
      /**
       * <pre>
       * Width of margin of error on each axis
       * </pre>
       *
       * <code>double dx = 13;</code>
       * @return The dx.
       */
      @java.lang.Override
      public double getDx() {
        return dx_;
      }
      /**
       * <pre>
       * Width of margin of error on each axis
       * </pre>
       *
       * <code>double dx = 13;</code>
       * @param value The dx to set.
       * @return This builder for chaining.
       */
      public Builder setDx(double value) {

        dx_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Width of margin of error on each axis
       * </pre>
       *
       * <code>double dx = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearDx() {
        bitField0_ = (bitField0_ & ~0x00000080);
        dx_ = 0D;
        onChanged();
        return this;
      }

      private double dy_ ;
      /**
       * <code>double dy = 14;</code>
       * @return The dy.
       */
      @java.lang.Override
      public double getDy() {
        return dy_;
      }
      /**
       * <code>double dy = 14;</code>
       * @param value The dy to set.
       * @return This builder for chaining.
       */
      public Builder setDy(double value) {

        dy_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>double dy = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearDy() {
        bitField0_ = (bitField0_ & ~0x00000100);
        dy_ = 0D;
        onChanged();
        return this;
      }

      private double dz_ ;
      /**
       * <code>double dz = 15;</code>
       * @return The dz.
       */
      @java.lang.Override
      public double getDz() {
        return dz_;
      }
      /**
       * <code>double dz = 15;</code>
       * @param value The dz to set.
       * @return This builder for chaining.
       */
      public Builder setDz(double value) {

        dz_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>double dz = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearDz() {
        bitField0_ = (bitField0_ & ~0x00000200);
        dz_ = 0D;
        onChanged();
        return this;
      }

      private double dtXy_ ;
      /**
       * <code>double dt_xy = 16;</code>
       * @return The dtXy.
       */
      @java.lang.Override
      public double getDtXy() {
        return dtXy_;
      }
      /**
       * <code>double dt_xy = 16;</code>
       * @param value The dtXy to set.
       * @return This builder for chaining.
       */
      public Builder setDtXy(double value) {

        dtXy_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>double dt_xy = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearDtXy() {
        bitField0_ = (bitField0_ & ~0x00000400);
        dtXy_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CLIPPY.control.Waypoint)
    }

    // @@protoc_insertion_point(class_scope:CLIPPY.control.Waypoint)
    private static final CLIPPY.control.WaypointOuterClass.Waypoint DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CLIPPY.control.WaypointOuterClass.Waypoint();
    }

    public static CLIPPY.control.WaypointOuterClass.Waypoint getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Waypoint>
        PARSER = new com.google.protobuf.AbstractParser<Waypoint>() {
      @java.lang.Override
      public Waypoint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Waypoint> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Waypoint> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CLIPPY.control.WaypointOuterClass.Waypoint getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CLIPPY_control_Waypoint_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CLIPPY_control_Waypoint_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Waypoint.proto\022\016CLIPPY.control\032\rUrgenc" +
      "y.proto\032\037google/protobuf/timestamp.proto" +
      "\"\372\001\n\010Waypoint\022-\n\ttimestamp\030\001 \001(\0132\032.googl" +
      "e.protobuf.Timestamp\0223\n\rwaypoint_type\030\002 " +
      "\001(\0162\034.CLIPPY.control.WaypointType\022(\n\007urg" +
      "ency\030\003 \001(\0162\027.CLIPPY.control.Urgency\022\t\n\001x" +
      "\030\007 \001(\001\022\t\n\001y\030\010 \001(\001\022\t\n\001z\030\t \001(\001\022\014\n\004t_xy\030\n \001" +
      "(\001\022\n\n\002dx\030\r \001(\001\022\n\n\002dy\030\016 \001(\001\022\n\n\002dz\030\017 \001(\001\022\r" +
      "\n\005dt_xy\030\020 \001(\001*V\n\014WaypointType\022\013\n\007UNKNOWN" +
      "\020\000\022\013\n\007NEUTRAL\020\001\022\014\n\010OBSTACLE\020\002\022\010\n\004FREE\020\003\022" +
      "\n\n\006TARGET\020\004\022\010\n\004SELF\020\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          CLIPPY.control.UrgencyOuterClass.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_CLIPPY_control_Waypoint_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CLIPPY_control_Waypoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CLIPPY_control_Waypoint_descriptor,
        new java.lang.String[] { "Timestamp", "WaypointType", "Urgency", "X", "Y", "Z", "TXy", "Dx", "Dy", "Dz", "DtXy", });
    CLIPPY.control.UrgencyOuterClass.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
