// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WaypointShufflers.proto

package CLIPPY.control;

public final class WaypointShufflers {
  private WaypointShufflers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027WaypointShufflers.proto\022\016CLIPPY.contro" +
      "l\032\016Waypoint.proto\032\033google/protobuf/empty" +
      ".proto2V\n\016WaypointServer\022D\n\014GetWaypoints" +
      "\022\026.google.protobuf.Empty\032\030.CLIPPY.contro" +
      "l.Waypoint\"\0000\0012U\n\rWaypointEater\022D\n\016Inges" +
      "tWaypoint\022\030.CLIPPY.control.Waypoint\032\026.go" +
      "ogle.protobuf.Empty\"\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          CLIPPY.control.WaypointOuterClass.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    CLIPPY.control.WaypointOuterClass.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
