// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ControlStyle.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ControlStyle_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ControlStyle_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/timestamp.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ControlStyle_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ControlStyle_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ControlStyle_2eproto;
namespace CLIPPY {
namespace control {
class ControlStyle;
struct ControlStyleDefaultTypeInternal;
extern ControlStyleDefaultTypeInternal _ControlStyle_default_instance_;
}  // namespace control
}  // namespace CLIPPY
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace CLIPPY {
namespace control {
enum ControlStyleEnum : int {
  NO_CONTROL = 0,
  MANUAL_DS = 1,
  MANUAL = 2,
  PLANNER = 3,
  ControlStyleEnum_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ControlStyleEnum_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ControlStyleEnum_IsValid(int value);
constexpr ControlStyleEnum ControlStyleEnum_MIN = static_cast<ControlStyleEnum>(0);
constexpr ControlStyleEnum ControlStyleEnum_MAX = static_cast<ControlStyleEnum>(3);
constexpr int ControlStyleEnum_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
ControlStyleEnum_descriptor();
template <typename T>
const std::string& ControlStyleEnum_Name(T value) {
  static_assert(std::is_same<T, ControlStyleEnum>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ControlStyleEnum_Name().");
  return ControlStyleEnum_Name(static_cast<ControlStyleEnum>(value));
}
template <>
inline const std::string& ControlStyleEnum_Name(ControlStyleEnum value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ControlStyleEnum_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool ControlStyleEnum_Parse(absl::string_view name, ControlStyleEnum* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ControlStyleEnum>(
      ControlStyleEnum_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class ControlStyle final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CLIPPY.control.ControlStyle) */ {
 public:
  inline ControlStyle() : ControlStyle(nullptr) {}
  ~ControlStyle() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ControlStyle(::google::protobuf::internal::ConstantInitialized);

  ControlStyle(const ControlStyle& from);
  ControlStyle(ControlStyle&& from) noexcept
    : ControlStyle() {
    *this = ::std::move(from);
  }

  inline ControlStyle& operator=(const ControlStyle& from) {
    CopyFrom(from);
    return *this;
  }
  inline ControlStyle& operator=(ControlStyle&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ControlStyle& default_instance() {
    return *internal_default_instance();
  }
  static inline const ControlStyle* internal_default_instance() {
    return reinterpret_cast<const ControlStyle*>(
               &_ControlStyle_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ControlStyle& a, ControlStyle& b) {
    a.Swap(&b);
  }
  inline void Swap(ControlStyle* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ControlStyle* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ControlStyle* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ControlStyle>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ControlStyle& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ControlStyle& from) {
    ControlStyle::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ControlStyle* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "CLIPPY.control.ControlStyle";
  }
  protected:
  explicit ControlStyle(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampFieldNumber = 1,
    kControlStyleFieldNumber = 2,
  };
  // .google.protobuf.Timestamp timestamp = 1;
  bool has_timestamp() const;
  void clear_timestamp() ;
  const ::google::protobuf::Timestamp& timestamp() const;
  PROTOBUF_NODISCARD ::google::protobuf::Timestamp* release_timestamp();
  ::google::protobuf::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::google::protobuf::Timestamp* value);
  void unsafe_arena_set_allocated_timestamp(::google::protobuf::Timestamp* value);
  ::google::protobuf::Timestamp* unsafe_arena_release_timestamp();

  private:
  const ::google::protobuf::Timestamp& _internal_timestamp() const;
  ::google::protobuf::Timestamp* _internal_mutable_timestamp();

  public:
  // .CLIPPY.control.ControlStyleEnum control_style = 2;
  void clear_control_style() ;
  ::CLIPPY::control::ControlStyleEnum control_style() const;
  void set_control_style(::CLIPPY::control::ControlStyleEnum value);

  private:
  ::CLIPPY::control::ControlStyleEnum _internal_control_style() const;
  void _internal_set_control_style(::CLIPPY::control::ControlStyleEnum value);

  public:
  // @@protoc_insertion_point(class_scope:CLIPPY.control.ControlStyle)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2, 1, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::Timestamp* timestamp_;
    int control_style_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ControlStyle_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ControlStyle

// .google.protobuf.Timestamp timestamp = 1;
inline bool ControlStyle::has_timestamp() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.timestamp_ != nullptr);
  return value;
}
inline const ::google::protobuf::Timestamp& ControlStyle::_internal_timestamp() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::google::protobuf::Timestamp* p = _impl_.timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Timestamp&>(::google::protobuf::_Timestamp_default_instance_);
}
inline const ::google::protobuf::Timestamp& ControlStyle::timestamp() const {
  // @@protoc_insertion_point(field_get:CLIPPY.control.ControlStyle.timestamp)
  return _internal_timestamp();
}
inline void ControlStyle::unsafe_arena_set_allocated_timestamp(::google::protobuf::Timestamp* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timestamp_);
  }
  _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:CLIPPY.control.ControlStyle.timestamp)
}
inline ::google::protobuf::Timestamp* ControlStyle::release_timestamp() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::Timestamp* released = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::google::protobuf::Timestamp* ControlStyle::unsafe_arena_release_timestamp() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:CLIPPY.control.ControlStyle.timestamp)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::Timestamp* temp = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  return temp;
}
inline ::google::protobuf::Timestamp* ControlStyle::_internal_mutable_timestamp() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::google::protobuf::Timestamp>(GetArenaForAllocation());
    _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(p);
  }
  return _impl_.timestamp_;
}
inline ::google::protobuf::Timestamp* ControlStyle::mutable_timestamp() {
  ::google::protobuf::Timestamp* _msg = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:CLIPPY.control.ControlStyle.timestamp)
  return _msg;
}
inline void ControlStyle::set_allocated_timestamp(::google::protobuf::Timestamp* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timestamp_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::google::protobuf::MessageLite*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  // @@protoc_insertion_point(field_set_allocated:CLIPPY.control.ControlStyle.timestamp)
}

// .CLIPPY.control.ControlStyleEnum control_style = 2;
inline void ControlStyle::clear_control_style() {
  _impl_.control_style_ = 0;
}
inline ::CLIPPY::control::ControlStyleEnum ControlStyle::control_style() const {
  // @@protoc_insertion_point(field_get:CLIPPY.control.ControlStyle.control_style)
  return _internal_control_style();
}
inline void ControlStyle::set_control_style(::CLIPPY::control::ControlStyleEnum value) {
  _internal_set_control_style(value);
  // @@protoc_insertion_point(field_set:CLIPPY.control.ControlStyle.control_style)
}
inline ::CLIPPY::control::ControlStyleEnum ControlStyle::_internal_control_style() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::CLIPPY::control::ControlStyleEnum>(_impl_.control_style_);
}
inline void ControlStyle::_internal_set_control_style(::CLIPPY::control::ControlStyleEnum value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.control_style_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace control
}  // namespace CLIPPY


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::CLIPPY::control::ControlStyleEnum> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::CLIPPY::control::ControlStyleEnum>() {
  return ::CLIPPY::control::ControlStyleEnum_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ControlStyle_2eproto_2epb_2eh
