# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ControlTarget.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'ControlTarget.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Urgency_pb2 as Urgency__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x43ontrolTarget.proto\x12\x0e\x43LIPPY.control\x1a\rUrgency.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfd\x01\n\rControlTarget\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tsystem_id\x18\x02 \x01(\t\x12(\n\x07urgency\x18\x03 \x01(\x0e\x32\x17.CLIPPY.control.Urgency\x12\x11\n\x07voltage\x18\x07 \x01(\x01H\x00\x12\x11\n\x07\x63urrent\x18\x08 \x01(\x01H\x00\x12\x12\n\x08position\x18\t \x01(\x01H\x00\x12\x12\n\x08velocity\x18\n \x01(\x01H\x00\x12\x16\n\x0c\x61\x63\x63\x65leration\x18\x0b \x01(\x01H\x00\x12\x10\n\x06\x61\x63tive\x18\x0c \x01(\x08H\x00\x42\x08\n\x06output\"\xa3\x01\n\x18MultiSystemControlTarget\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12(\n\x07urgency\x18\x02 \x01(\x0e\x32\x17.CLIPPY.control.Urgency\x12.\n\x07targets\x18\x03 \x03(\x0b\x32\x1d.CLIPPY.control.ControlTargetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ControlTarget_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTROLTARGET']._serialized_start=88
  _globals['_CONTROLTARGET']._serialized_end=341
  _globals['_MULTISYSTEMCONTROLTARGET']._serialized_start=344
  _globals['_MULTISYSTEMCONTROLTARGET']._serialized_end=507
# @@protoc_insertion_point(module_scope)
