services:
  talker:
    image: osrf/ros:humble-desktop
    command: ros2 run demo_nodes_cpp talker
    networks:
      - clippy_ros
  listener:
    image: osrf/ros:humble-desktop
    command: ros2 run demo_nodes_cpp listener
    depends_on:
      - talker
    networks:
      - clippy_ros

networks:
  clippy_ros:
    external: true
