[package]
name = "hello-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.4"
prost-types = "0.13.4"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.12.3"

[build-dependencies]
prost-build = "0.13.4"
tonic-build = "0.12.3"