<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Null.proto

namespace CLIPPY\PBNull;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>CLIPPY.null.Null</code>
 */
class PBNull extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBNull::initOnce();
        parent::__construct($data);
    }

}

